spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/springboot
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8090

kafka:
  bootstrap:
    server: localhost:9092


