spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

kafka:
  bootstrap:
    server: localhost:9092
  prev-topic: accumulated-value-of-diskio
  result-topic: calculated-value-of-diskio
